#!/bin/csh

mail -s "Conference Alert" perlis@cs.umd.edu < Message
mail -s "Conference Alert" darsana@cs.umd.edu < Message
mail -s "Conference Alert" yuan@cs.umd.edu < Message
mail -s "Conference Alert" yoshi@umiacs.umd.edu < Message
mail -s "Conference Alert" kpurang@cs.umd.edu < Message




