(defvar *prefix* (expand-file-name "scripts/prefix-1.html"))
(defvar *suffix* (expand-file-name "scripts/suffix-1.html"))

(defun build (&optional directory)
  (let* ((directory (or directory "."))
	 (files (cddr (directory-files directory))))
    (dolist (file files)
      (let* ((truename (expand-file-name (concat directory "/" file)))
	     (pathname (file-name-directory truename))
	     (filename (file-name-nondirectory truename))
	     (basename (file-name-sans-extension filename))
	     (extension (file-name-extension filename)))
	(cond
	  ((file-directory-p truename)
	   (build truename))
	  ((= ?\_ (aref basename 0))
	   (let ((newfile (concat directory "/" (substring basename 1) "." extension)))
	     (with-temp-file newfile
	       (insert-file *suffix*)
	       (insert-file truename)
	       (insert-file *prefix*)))))))))